#! /bin/csh -f
cp 	lj.model        	fort.25
foreach rho (0.70)
  echo " --- rho ${rho} "  		>> out
  echo " --- rho ${rho} "
  cat > fort.15  <<endofdata
  ibeg    nequil     prod    nsamp  iseed
  0       1000       10000   1      368675
  dr
  0.09
  ndispl   nLambda   nGhosts nWidomCycle
  50       20        10      10000
  npart    temp      rho
  100      2.0       ${rho}
  runWidom runTDI    sigmamod
  1        1         1
endofdata
 cp 	lj.res          	fort.11
 cp 	lj.model          	fort.25
 echo  "Running ../Source/mc_nvt"
 time  ../Source/mc_nvt
 mv   fort.10           out
 cp 	fort.21         	lj.res
 cp 	fort.66         	lj.prt
 #perform block analysis
 cp 	lj.prth 		fort.31
 mv  	lj.prt 		fort.32
 cp   fort.32     enPresWidom.dat
 mv   fort.44     lambdaResults.dat
 mv   fort.40     sigmaVrho.dat
 ../Block/block  	 		>>& out2
 rm fort.*
end
exit
