#!/bin/zsh
let "rhoSigmaOG = 0.7"
let "sigma = 0.9"
for ((sigma = 0.95; sigma <= 1.05; sigma=sigma+0.01)); do
   let "rho = $rhoSigmaOG * $sigma * $sigma * $sigma"
   echo " --- sigma   $sigma"
   echo " --- rhoOG   $rhoSigmaOG "
   echo " --- rho     ${rho} "        >> out
   echo " --- rho     ${rho} "
   echo " ---------------------------"
   cat > fort.15  <<endofdata
   ibeg    nequil     prod    nsamp  iseed
   0       1000       10000   1      368675
   dr
   0.09
   ndispl   nLambda   nGhosts nWidomCycle
   50       1000      10      100000
   npart    temp      rho
   100      2.0       ${rho}
   runWidom runTDI    sigmaMod
   1        0         ${sigma}
endofdata
   cp    lj.res             fort.11
   cp    lj.model             fort.25
   echo  "Running ../Source/mc_nvt"
   time  ../Source/mc_nvt     >>& "out$sigma"
   cp    fort.21            lj.res
   cp    fort.66            lj.prt
   mv   fort.66             data.dat
   mv   fort.10             WidomData.dat
   #perform block analysis
   cp   lj.prth        fort.31
   mv   lj.prt         fort.32
   cp   fort.32        presEn.dat
   cat  fort.40    >>  chempotVdensity.dat
   ../Block/block            >>& "block$sigma"
   rm fort.*
done
